### PR TITLE
Add localtime

### PR DESCRIPTION
**Pull request by charlax**
screen shot 2015-03-05 at 3 47 56 pm

### CODE REVIEW

**Comment by charlax** [comment]
Are you interested in this PR? What do you think of the idea?

**Comment by morozgrafix** [comment]
Local time support is exactly what I was looking for. 
@charlax Had a little bit of a problem clipboard copy of a local timestamp. Here is a small fix to make sure arg is populated with local timestamp and timezone.

```
    # Local time
    arrow_time = arrow.get(value.datetime).to('local')
    item_value = arrow_time.datetime.strftime("%a, %d %b %Y %H:%M:%S")
    timezone = arrow_time.datetime.strftime('%Z')
    results.append(alfred.Item(
        title=item_value,
        subtitle=u'Local time (%s)' % timezone,
        attributes={
            'uid': alfred.uid(index),
            'arg': item_value + " " + timezone,
        },
        icon='icon.png',
    ))
    index += 1
```

before fix: `[INFO: alfred.workflow.input.scriptfilter] Processing output 'alfred.workflow.output.clipboard' with arg '1434139607'`
after fix: `[INFO: alfred.workflow.input.scriptfilter] Processing output 'alfred.workflow.output.clipboard' with arg 'Fri, 12 Jun 2015 13:06:47 PDT'`

Thanks.

**Comment by jnovack** [comment]
Goodness, what is arrow/arrowfactory and can you do this without it??? That's a lot of add.

**Comment by charlax** [comment]
Was just the fastest way for me. I think we can close this PR, this is pretty old :)

**Comment by jnovack** [comment]
I wanted to refresh the workflow all around the web with it.  I use this original workflow DAILY and wanted to add more features.  

https://media.giphy.com/media/1cv7Gwf0Utdeg/giphy.gif

**Pull request closed without merging**
